package com.roleservice.roles.entity.common;

public enum PermissionsType {
	
	CREATE("CREATE"), READ("READ"), UPDATE("UPDATE"), DELETE("DELETE"), AUTHORISE("AUTHORISE"), REVIEW("REVIEW"),
	APPROVE("APPROVE"), SUBMIT("SUBMIT"), VOID("VOID"), ACCOUNT_VIEW("ACCOUNT_VIEW"), TRANSACTIONS("TRANSACTIONS"),
	PERMISSIONS("PERMISSIONS"),UPLOAD("UPLOAD"), ADD("ADD"), ALLOW("ALLOW"), BANK("BANK"), APPROVE_NOBANK("APPROVE_NOBANK"),
	FINANCE("FINANCE"), DYNAMIC_NEGOTIATION("DYNAMIC_NEGOTIATION"), SEND("SEND"), CARDPAYMENT("CARDPAYMENT"),
	AUTH_DELETE_DEL("AUTH_DELETE_DEL"),QB_ACCESS("QB_ACCESS"), VIEW_CARD("VIEW_CARD"), USER_SETTINGS("USER_SETTINGS"),
	BANK_SETTINGS("BANK_SETTINGS"), HD_SETTINGS("HD_SETTINGS"), CMS("CMS"), VIEW("VIEW"), INVOICE_SUBMIT("INVOICE_SUBMIT"),
	VERIFY("VERIFY"),VIEW_BUSINESS_SCREENS("VIEW_BUSINESS_SCREENS"), ACH_FILES_CREATE("ACH_FILES_CREATE"),
	ACH_FILES_VIEW("ACH_FILES_VIEW"),CHECK_FILES_VIEW("CHECK_FILES_VIEW"), CHECK_FILES_DOWNLOAD("CHECK_FILES_DOWNLOAD"),
	Bill_FINANCING_FILES_VIEW("Bill_FINANCING_FILES_VIEW"),Bill_FINANCING_FILES_UPLOAD("Bill_FINANCING_FILES_UPLOAD"),
	DOWNLOAD("DOWNLOAD"), SEND_EMAIL("SEND_EMAIL"), FUNDING_DEBIT_AR("FUNDING_DEBIT_AR"), FUNDING_DEBIT_AP("FUNDING_DEBIT_AP"),
	INVOICE_PAYMENT_AR("INVOICE_PAYMENT_AR"), INVOICE_PAYMENT_AP("INVOICE_PAYMENT_AP"), QB_FAILED_SYNC_AR("QB_FAILED_SYNC_AR"),
	QB_FAILED_SYNC_AP("QB_FAILED_SYNC_AP"), ADD_PRODUCT("ADD_PRODUCT"), EDIT_PRODUCT("EDIT_PRODUCT"),
	VIEW_PRODUCT("VIEW_PRODUCT"), INVOICE_CAPTURE_DELETE("INVOICE_CAPTURE_DELETE"), STATUS("STATUS"), VERIFICATION("VERIFICATION"),
	TEST("TEST"), BUSINESS_SCREENS_READ("BUSINESS_SCREENS_READ"),
	BUSINESS_SCREENS_READ_WRITE("BUSINESS_SCREENS_READ_WRITE");
	
	private String  permissionType;
	private PermissionsType(String type) {
		this.permissionType = type;
	}
	
}
